fileobj = open('test.txt')
x = fileobj.tell()  
print(fileobj.tell())
line = fileobj.readline()
while line:
  print(line)
  #print(fileobj.seek(x))
  fileobj.seek(x)
  print(fileobj.readline())
  #print(line)
  x = fileobj.tell()  
  print(fileobj.tell())
  line = fileobj.readline()
fileobj.close()